serviceName: minions

jaeger:
  disabled: false

stress:
  workflow:
    totalLaunchCount: 10000
    routineCount: 1
    chainSequence: 4
    activitySleepMin: 1
    activitySleepMax: 60

logging:
  level: info
  stdout: true

metrics:
  m3:
    hostPort: 127.0.0.1:9052
    service: cherami-stress
