serviceName: minions

logging:
  level: info
  stdout: true

jaeger:
  disabled: false

stress:
  workflow:
    totalLaunchCount: 1000
    routineCount: 20
    chainSequence: 4
    activitySleepMin: 1
    activitySleepMax: 60
  metrics:
    m3:
      hostPort: 127.0.0.1:9052
      service: cherami-stress
